coverage:
  status:
    project:
      default:
        threshold: 0.2

  ignore:
    - doc/
    - examples/
    - utils/
    - src/valgrind/
    - tests/

comment:
  layout: "diff, files"
  behavior: default
  require_changes: yes
